### ISSUE TITLE
missing [Your Region] from Lambda function name

### ISSUE THREAD

**Issue by crow15** [awslabs/aws-lambda-zombie-workshop#25]
10. In the dropdowns for the Pre authentication and Post confirmation triggers, select the Lambda function named "[Your CloudFormation Stack name]-CognitoLambdaTrigger". Click Next step.

should be

10. In the dropdowns for the Pre authentication and Post confirmation triggers, select the Lambda function named "[Your CloudFormation Stack name]-CognitoLambdaTrigger-[Your Region]". Click Next step.

**Comment by kylesomers** [comment]
Resolved with this [commit](https://github.com/awslabs/aws-lambda-zombie-workshop/commit/4ec76a0a4d0b94164ced78e6d0a8d2c9cdbb4e00)
