### ISSUE TITLE
should say Authentication not Authenticated providers

### ISSUE THREAD

**Issue by crow15** [awslabs/aws-lambda-zombie-workshop#26]
15. Click the black dropdown arrow in the section titled "Authenticated providers".
 
should be

15. Click the black dropdown arrow in the section titled "Authentication providers".

**Comment by kylesomers** [comment]
Resolved with this [commit](https://github.com/awslabs/aws-lambda-zombie-workshop/commit/4ec76a0a4d0b94164ced78e6d0a8d2c9cdbb4e00)
