### ISSUE TITLE
lab 1: lambda function name not quite right

### ISSUE THREAD

**Issue by crow15** [awslabs/aws-lambda-zombie-workshop#27]
7. For the Lambda Function field, begin typing "gettalkers" in the text box. In the auto-fill dropdown, select the function that contains "GetTalkersFromDynamoDB" in the name. It should look something like this.... [CloudformationTemplateName]-GetTalkersFromDynamoDB-[XXXXXXXXXX].

should be (note lambda function name)

7. For the Lambda Function field, begin typing "gettalkers" in the text box. In the auto-fill dropdown, select the function that contains "GetTalkersFromDynamoDB" in the name. It should look something like this.... [CloudformationTemplateName]-[XXXXXXX]-GetTalkersFromDynamoDB-[Your Region].

**Comment by crow15** [comment]
same issue for 

12. Perform Steps 4-10 again as you did for the GET method. However, this time when you are selecting the Lambda Function for the Integration Request, you'll type "writetalkers" in the auto-fill and select the function that looks something like this... [CloudformationTemplateName]-WriteTalkersToDynamoDB-[XXXXXXXXXX]

**Comment by kylesomers** [comment]
Resolved with this [commit](https://github.com/awslabs/aws-lambda-zombie-workshop/commit/4ec76a0a4d0b94164ced78e6d0a8d2c9cdbb4e00)
