### ISSUE TITLE
Cognito triggers don't populated user's phone numbers in DynamoDB

### ISSUE THREAD

**Issue by awochna** [awslabs/aws-lambda-zombie-workshop#28]
This causes the second lab to throw errors about the user's phone number not being verified. It still puts the received text message into the database because the function doesn't stop execution after that error. 

Related to this, `Twilio/TwilioProcessing.js` at line 102 doesn't check to see if `phoneAuthorized` is true, it just sets it to true and continues to post to the chat service. This is why the workshop appears complete, even though the user will receive an message on their phone that their phone number is not authorized.

**Comment by kylesomers** [comment]
If you can provide some details about how the trigger didn't populate the Dynamo Table, that would be useful for replicating the error. Haven't found this issue in testing. Did notice the Lambda function (TwilioProcessing) was incorrectly handling the phone number check like you mentioned and have just pushed a fix for this in latest [commit](https://github.com/awslabs/aws-lambda-zombie-workshop/commit/728420b246935e5a2a5014797fa6f9856c1404e2)

**Comment by awochna** [comment]
In testing, did you receive a message back to your phone that your phone number is not authorized? Did the Lambda function log any errors?

**Comment by kylesomers** [comment]
In testing the response back to the phone was as expected and it populated in the room. There were several bug fixes to the UI and application a week or so ago so if you tested prior to then, I'd suggest re-launching stack and testing again if you still see issues. Apologize for not catching this earlier!
