### ISSUE TITLE
Adding CF Template of Seoul Region

### ISSUE THREAD

**Issue by channy** [awslabs/aws-lambda-zombie-workshop#29]
Zombie Workshop in Seoul will be held on October. We need to add CF template of Seoul region for https://aws.amazon.com/ko/events/zombie-reg-seoul-oct-2016/.

**Comment by kylesomers** [comment]
Support for Seoul added with [commit 75f69d2](https://github.com/awslabs/aws-lambda-zombie-workshop/commit/75f69d264d9ac24e7ef06b29f7cbba2d83cb8cf8)
