### ISSUE TITLE
CloudFormation Template in S3 isn't up to date

### ISSUE THREAD

**Issue by paulfryer** [awslabs/aws-lambda-zombie-workshop#43]
The Cognito region mapping for us-east-2 is pointing to us-east-1, but should be pointing to us-east-2. From the S3 CF file:

`       "us-east-2": {
        "S3Endpoint": "https://s3-us-east-2",
        "S3ContentsBucket": "aws-zombie-workshop-us-east-2",
        "CognitoRegion": "us-east-1"
      },`

The correct value seems to already be checked into source code here:
https://github.com/awslabs/aws-lambda-zombie-workshop/blob/master/CloudFormation/CreateZombieWorkshop.json#L30

So it looks like we just need to deploy the update to S3 from Github.

**Comment by kylesomers** [comment]
Great catch Paul and you are right.
I've updated the templates in our hosting S3 buckets to fix this.
