### ISSUE TITLE
Cloud Formation Deployment - ZombieLabLambdaRole   - Syntax errors in policy

### ISSUE THREAD

**Issue by DavidRollinsSlalom** [awslabs/aws-lambda-zombie-workshop#44]
Cloud Formation Error

After following the instructions to lauch cloud formation I get this error as part of the deployment.

Syntax errors in policy: {"Version":"2012-10-17","Statement":[{"Action":["sts:AssumeRole","sts:AssumeRoleWithWebIdentity"],"Effect":"Allow","Principal":{"Service":["lambda.amazonaws.com","apigateway.amazonaws.com"],"Federated":"cognito-identity.amazonaws.com"}}]}

![image](https://cloud.githubusercontent.com/assets/3731733/24305987/e199e99c-108c-11e7-8f96-3634de2588c6.png)

As I understand it there may be an alternative script to automate the build.  I'd like to request changes to the deploy button or extra instructions to specify where to pull the alternative build script.

**Comment by gadams999** [comment]
This has been resolved and the deployment script will now work properly. Tested today in us-east-1 and us-east-2.
