### ISSUE TITLE
ZombieLabLambdaRole IAM Policy refers to "elasticsearch", not "es"

### ISSUE THREAD

**Issue by spigaj** [awslabs/aws-lambda-zombie-workshop#54]
The CFn template that creates the ZombieLabLambdaRole IAM policy (aws-lambda-zombie-workshop/CloudFormation/CreateZombieWorkshop.json) defines "elasticsearch" as the action (lines 122-126):
`            {
              "Effect": "Allow",
              "Action": ["elasticsearch:*"],
              "Resource": ["*"]
            },
`

The documentation (https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-access-policies) states that this should be "es" - not "elasticsearch".

As it the CFn template currently stands, Lab 3 does not work as the Lambda function does not have the rights to post to the ElasticSearch endpoint:

> "Message": "User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/zombiestack-ZombieLabLambdaRole-XXXXXXXXXXXX/zombiestack-ESsearch is not authorized to perform: es:ESHttpPost on resource: zombiestack-zombiemessages"

**Comment by kylesomers** [comment]
Modified the permissions in the CFN template and updated it in the repo thanks for bringing that to our attention.
